### ISSUE TITLE
Error in Planning module: 'BoxDetection' object has no attribute 'position'

### ISSUE THREAD

**Issue by srajangoyal** [avstack-lab/lib-avstack-core#3]
Hey guys, I'm getting this error in planning module.
Specifically, I've built a custom ego in Carla-sandbox, with 3dCamera and AdaptiveCruiseControl.
I can provide more details in case you need it.

Could you please check?

Here is the back trace for your reference, if it helps:

WARNING:root:'BoxDetection' object has no attribute 'position'
Traceback (most recent call last):
File "exec_standard.py", line 81, in main
done = carla_manager.tick()
File "/home/srajan/carla-sandbox/submodules/lib-avstack-api/avapi/carla/simulator/manager.py", line 88, in tick
done = self.ego.tick(self.t_elapsed, self.frame, self.infrastructure)
File "/home/srajan/carla-sandbox/submodules/lib-avstack-api/avapi/carla/simulator/ego.py", line 298, in tick
ctrl = self.algorithms.tick(
File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/ego/vehicle.py", line 37, in tick
control = self._tick_modules(
File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/ego/vehicle.py", line 193, in _tick_modules
self.plan = self.planning(self.plan, self.environment, ego_state, dets_3d_cam, dets_2d, lanes)
File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/modules/planning/vehicle.py", line 131, in call
obj_follow = components.get_object_to_follow(ego_state, objects_3d, lane_lines) #### Hence, it works only for 3dObjects
File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/modules/planning/components.py", line 32, in get_object_to_follow
obj.position
AttributeError: 'BoxDetection' object has no attribute 'position'
Done!
'''

**Comment by roshambo919** [comment]
The planning modules that are currently integrated are not very good, FYI. I've mostly focused on sensor fusion (perception and tracking). Feel free to put up PRs for enhancements.

Nevertheless, I may have fixed this in the latest update [here](https://github.com/avstack-lab/lib-avstack-core/blob/d54126536b0d6a652dff38b2de2d6143013cc8e6/avstack/modules/planning/components.py#L31)

**Comment by roshambo919** [comment]
Yeah it does not work very well. It's mostly a reference point for you to start your own.
