### ISSUE TITLE
Error:: Perception Module: 'LidarMeasurement' object has no attribute 'tofile'

### ISSUE THREAD

**Issue by srajangoyal** [avstack-lab/lib-avstack-core#4]
Hey guys, I'm getting this error while using Lidar for 3Dobject detection.
I had to make some minor updates (mainly dependencies) in the code to get to this error.

Could you please check?

Here is the back trace for your reference:

WARNING:root:'LidarMeasurement' object has no attribute 'tofile'
Traceback (most recent call last):
File "exec_standard.py", line 81, in main
done = carla_manager.tick()
File "/home/srajan/carla-sandbox/submodules/lib-avstack-api/avapi/carla/simulator/manager.py", line 88, in tick
done = self.ego.tick(self.t_elapsed, self.frame, self.infrastructure)
File "/home/srajan/carla-sandbox/submodules/lib-avstack-api/avapi/carla/simulator/ego.py", line 298, in tick
ctrl = self.algorithms.tick(
File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/ego/vehicle.py", line 37, in tick
control = self._tick_modules(
File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/ego/vehicle.py", line 293, in _tick_modules
dets_3d = self.perception["object_3d"](
File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/modules/perception/base.py", line 34, in call
detections = self._execute(
File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/modules/perception/object3d.py", line 95, in execute
result = self.run_mm_inference(
File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/modules/perception/object3d.py", line 125, in run_mm_inference
data.data.tofile(data_file)
AttributeError: 'LidarMeasurement' object has no attribute 'tofile'

**Comment by roshambo919** [comment]
I believe I've patched this in the commit [4e22aab](https://github.com/avstack-lab/lib-avstack-core/commit/4e22aab7c7f97ed51b92025c939bb8a31f624646)

However I can't yet completely be sure because lidar detection models are not working right now for carla. For that, stay tuned at issue #7. I'll keep it updated there.
